<!DOCTYPE html>
<html>
  <head>
    <title>My Website</title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
    <header>
      <h1>Welcome to My Website</h1>
      <nav>
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Services</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </nav>
    </header>
    <main>
      <section>
        <h2>About Me</h2>
        <p>Hi, my name is John Doe and I'm a web developer.</p>
      </section>
      <section>
        <h2>Services</h2>
        <ul>
          <li>Web Design</li>
          <li>Web Development</li>
          <li>SEO</li>
        </ul>
      </section>
      <section>
        <h2>Contact</h2>
        <p>Email: john.doe@example.com</p>
        <p>Phone: 555-555-5555</p>
      </section>
    </main>
    <footer>
      <p>&copy; 2023 My Website</p>
    </footer>
  </body>
</html>


